version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./firebase-admin-key.json:/app/firebase-admin-key.json
    env_file:
      - ./.env
    container_name: consent
    restart: always
